# Site Settings
baseurl: ""
url : "https://sup2is.github.io"

# Blog Settings
theme_settings :
  title : Sup2's blog
  favicon : ./favicon.ico

  # Profile Settings
  profile :
    image : assets/img/main.jpg
    username : HyeonSeop Choi
    description : ì•ˆë…•í•˜ì„¸ìš” ì €ëŠ” Javaì™€ Kotlinì„ ì¢‹ì•„í•˜ëŠ” ê°œë°œì ì…ë‹ˆë‹¤. ì´ ë¸”ë¡œê·¸ëŠ” ë°°ìš°ê³  ì‹¶ì€ ê¸°ìˆ ì´ë‚˜ TIL ê´€ë ¨ ê¸€ì„ í¬ìŠ¤íŒ…í•˜ëŠ” ë¸”ë¡œê·¸ì…ë‹ˆë‹¤. ë¶€ì¡±í•œ ì‹¤ë ¥ì´ë¼ ì˜ì–´ ë¬¸ì¥ì— ì˜¤ì—­ì´ ìˆì„ ìˆ˜ ìˆê³  ì˜ëª»ëœ ì§€ì‹ì„ ì „íŒŒ í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤. í”¼ë“œë°±ì€ ì–¸ì œë‚˜ í™˜ì˜í•©ë‹ˆë‹¤. ê°ì‚¬í•©ë‹ˆë‹¤. ğŸ˜€
    experience :
      - start : 2018-09-17
        end : 2020-04-14
        experience : Paycoms - Backend Developer
      - start : 2020-05-06
        experience : ESTGames - Backend Developer
        end : 2021-05-14
      - start : 2021-05-31
        experience : 42dot - Backend Developer
        end : 2022-06-02
      - start : 2022-06-07
        experience : Naver Financial - Backend Developer

    skills : 
      - skill : Java
        value : 80  # Percent value
      - skill : Spring
        value : 80  # Percent value
      - skill : RDB
        value : 70  # Percent value
      - skill : Kotlin
        value : 70  # Percent value
      - skill : NoSQL
        value : 50  # Percent value
      - skill : HTML5 & CSS3 & JQuery
        value : 40  # Percent value
      - skill : Javascript
        value : 30  # Percent value
      - skill : Vue
        value : 30  # Percent value


  # Icons
  icons :
    email: dev.sup2is@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: sup2is
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : sup2is

# Pagination
paginate: 7
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
  
lang: ko_KR

google_analytics: UA-136379787-1
